auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Liuzhou
url: http://zzghost.github.io
feed: /atom.xml
author_info: <a href="http://zzghost.github.io/">Liuzhou</a>
